services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: undiscord:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/archives:/data/archives
    environment:
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_VALHALLA_CATEGORY_ID=${DISCORD_VALHALLA_CATEGORY_ID}
      - DISCORD_COMMAND_CENTER_ID=${DISCORD_COMMAND_CENTER_ID}
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - API_KEY=${API_KEY}
